name: our Release
on:
  release:
    types: [published]
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "name=${{ github.event_name }}"
      - run: echo "action=${{ github.event.action }}"
      - run: echo "ref_name=${{ github.event.ref_name }}"
